import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LoginComponent from "@/components/login";
import CalculatorInterface from "@/components/calculator-interface";
import { useState } from "react";

export default function Home() {
  const [checkLogin, setCheckLogin] = useState(false);
  const handleLogin = () => {
    setCheckLogin(true);
  };
  return (
    <div className="homepage-container" style={{top:0}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <h2 style={{ color: "white", paddingTop: "2em", marginLeft: "3em" }}>
        Welcome to Balance Calculator
      </h2>

      {checkLogin ? (
        <></>
      ) : (
        <div className="container-fluid" style={{ marginTop: "10em" }}>
          <div className="row">
            <div className="col-6">
              <LoginComponent onLogin={handleLogin} />
            </div>
          </div>
        </div>
      )}

      {checkLogin && (
        <div className="container-fluid animate__animated animate__fadeInDown" style={{ marginTop: "0em" }}>
          <div className="row">
            <div className="col-6">
              <CalculatorInterface />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
